// <auto-generated />
using FinderNET.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinderNET.Database.Migrations
{
    [DbContext(typeof(FinderDbContext))]
    partial class FinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FinderNET.Database.Models.Guild", b =>
                {
                    b.Property<ulong>("guildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.HasKey("guildId");

                    b.ToTable("Guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
